name: Upload File to S3

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Upload file to S3
      run: |
        aws s3 cp cfn/caesar_cipher.py s3://${{ secrets.AWS_S3_BUCKET }}/ --region us-east-1
