name: Echo Secret Workflow

on: workflow_dispatch

jobs:
  echo-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo the secret
        run: |
          echo "Printing the secret:"
          echo "${{ secrets.AWS_ACCESS_KEY_ID  }}"
          
          
