name: SAM Deploy Workflow

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS credentials (using GitHub secrets)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Install SAM CLI
      - name: Install SAM CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install aws-sam-cli

      # Build the SAM application (template located in cfn-scripts/)
      - name: Build SAM application
        run: sam build --template cfn/template.yaml

      # Deploy the SAM application (template located in cfn-scripts/)
      - name: Deploy SAM application
        run: |
          sam deploy --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --region ap-south-1 --template-file cfn/template.yaml --stack-name my-github-actions-stack
